#pragma once

#define DEFAULT_UNIFORM_MODEL_NAME "model"
#define DEFAULT_UNIFORM_VIEW_NAME "view"
#define DEFAULT_UNIFORM_PROJ_NAME "proj"

#define DEFAULT_AMBIENT_COLOR glm::vec3(0.2f)
#define DEFAULT_DIFFUSE_COLOR glm::vec3(0.4f)
#define DEFAULT_SPECULAR_COLOR glm::vec3(1.0f)

#define DEFAULT_LIGHT_POSITION glm::vec3(1.0f)
#define DEFAULT_LIGHT_DIRECTION glm::vec3(0.0f)


#define DEFAULT_LIGHT_CONSTANT 1.0f
#define DEFAULT_LIGHT_LINEAR 0.09f
#define DEFAULT_LIGHT_QUADRATIC 0.032f

#define DEFAULT_SPOTLIGHT_CUTOFF 50.0f
#define DEFAULT_SPOTLIGHT_OUTERCUTOFF 70.0f